services:

  db:
    image: mariadb:latest
    container_name: mariadb-blog
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql/data:rw
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'blog_db'
    networks:
      - weblog

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-blog
    depends_on:
      - db
    ports:
      - 8085:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - weblog

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    container_name: mailpit-adapa
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - weblog
###< symfony/mailer ###
  redis:
    image: redis:5-alpine
    container_name: redis-adapa
    ports: [6379]
    networks:
      - weblog

volumes:
  db-data:
networks:
  weblog:
