version: '3'

services:

  database:
    image: mariadb
    container_name: mariadb-blog
    ports:
      - 3308:3306
    restart: always
    volumes:
      - db-data:/var/lib/mysql/data:rw
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
      MARIADB_DATABASE: 'blog_db'

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-blog
    restart: always
    depends_on:
      - database
    ports:
      - 8081:80
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: 'root'

  rabbitmq:
    image: rabbitmq:3.7-management
    container_name: rabbitmq-blog
    ports: [ 5672, 15672 ]

  portainer-ce:
    image: portainer/portainer-ce
    container_name: "portainer-ce-mint"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  db-data:


